fix package names in log folder
in the newer nixpkgs-review version the log now names
the package like PACKAGE-SYSTEM.log which will cause errors
like

```
Package is missing a meta section. If the package is using runCommand
please make sure to inherit or create a
meta section.

error: AttrPathNotFound Packages in
‘/nix/store/vx1psq29l9rhlvq01rf67wnx2avk0z6d-nixpkgs’ do not contain
‘k9s-x86_64’ attribute.
```

this commit now uses regex to filter the most common system names
(as defined by nixpkgs-review upstream[1])

[1]: https://github.com/Mic92/nixpkgs-review?tab=readme-ov-file#review-changes-for-other-operating-systemsarchitectures

Signed-off-by: Florian Brandes <florian.brandes@posteo.de>